### ISSUE TITLE
2GB SD Card Support

### ISSUE THREAD

**Issue by suchipi** [danielkraak/GC-Loader#14]
Hello,

I'm using a GCLoader PNP. It only reports a disc in the drive if I put an SD card in it that is 4GB or higher.

I'd like to use a smaller SD card I have (2GB), because I keep all my content on a larger card attached to serial port 2 (via an SD2SP2), so the SD card in the GCLoader just has Swiss on it.

Is the 4GB minimum a hard limit? Or could I recompile and flash the firmware to allow 2GB cards?

**Comment by kingjinxy** [comment]
I believe that 4GB may be a limit, but I have to ask. Why would you put everything on the SD2SP2 when you could just put it on the GCLoader? The disc drive bus is faster than SP2 and the Memory Card slots, so you should have less problems.

**Comment by suchipi** [comment]
I got a ton of 2GB sd cards for super cheap so I wanted to make a kinda artsy crafty style project where I printed custom game labels on them and put one iso on each

**Comment by kingjinxy** [comment]
Have you updated to firmware 1.1.2? Perhaps it could fix the issue.

It is strangely not listed here on GitHub, but rather here:
https://www.gc-loader.com/firmware-updates/

**Comment by danielkraak** [comment]
Should be fixed in the upcoming update.

**Comment by suchipi** [comment]
Awesome, thank you! To clarify, was this fixed in 1.1.2, or in an as-of-yet-unreleased version?

**Comment by suchipi** [comment]
Ah, nevermind, I see now [here](https://gc-loader.com/firmware-updates/) that 1.1.2 is an older version; it was just recently added to this repo.
