### ISSUE TITLE
Distorted sound that goes away on its own on 1.1.2

### ISSUE THREAD

**Issue by gtsamour** [danielkraak/GC-Loader#16]
Hi,

I had this issue on 1.1.0 as well (when I got my GC-Loader) but on 1.1.2 this issue is supposed to be fixed according to "Fixed random corrupted audiostreaming sound".

So... I encounter the issue where on games that doesn't necessarily have audiostreaming (Like Mario Kart Double Dash, Mario Party or Rogue Squadron II) there are some instances, (not very often though) that the audio gets distorted for a short period of 3-4 seconds. After that it fixes itself and everything sounds normal again. The volume of this distortion isn't louder than the rest of the audio and it doesn't happen on a specific part of the game every time.

It sounds like a "digital" kind of distortion, I don't know how else to describe it... but it has occured on different games and it doesn't seem to have anything to do with the audio streaming issues that were known on earlier firmwares.

The ISOs are Redump and I also have Carby,
The SDs I'm using are Kingston 512GB and 256GB.

Anyone else encountered something like this?

**Comment by gtsamour** [comment]
Nevermind, issue resolved.
It was the off spec audio sampling rate the Gamecube produces and can result such issues on some TVs if fed in a digital form (through the HDMI by an adapter like Carby and such).

In analog form though (ex an RGB scart cable) it causes no troubles.

Tried it on another TV and no distortions there.

**Comment by tjanas** [comment]
CRT FTW

**Comment by Extrems** [comment]
If you have GCVideo-DVI v3.0 or later, you can turn on the sample rate hack. Note this is a crude method of downsampling.

**Comment by gtsamour** [comment]
I did try the sample rate hack, it takes more time for the distortion to appear but when it does, its louder and takes a lot more time to fix itself.
