### ISSUE TITLE
Swiss not loading

### ISSUE THREAD

**Issue by TallGlassOfBruce** [danielkraak/GC-Loader#17]
The disc could not be read error appears. The GC loader has two red lights on? I have a Sandisk Ultra Plus Micro SD card of 128GB. It is formatted to Fat32. I have a ntscUSA gamecube, so I used that iso. I renamed it boot. I don't know what's wrong

**Comment by DefKonZer0** [comment]
I had the same issue as you did, I had just bought it via AliExpress. First it wouldn't read the ISOs via Swiss which I followed the prompts and formatted to a FAT32 SD card if 128GB, I tested a demo disc ISO but no luck. Then I realized that I had to update the GC Loader which failed miserably, it tells me error during update process 5-6 times. Then the next day I went with another SD card and all of a sudden it stopped working and had 2 lights solid on the GC loader

**Comment by DefKonZer0** [comment]
![CB8D2C82-9423-497F-8944-4065BBB25B57](https://user-images.githubusercontent.com/82219393/114189618-0194fd80-9910-11eb-8197-11eb262d7f8c.jpeg)
![389A1144-FBD1-49E8-A920-096053291BDC](https://user-images.githubusercontent.com/82219393/114189620-02c62a80-9910-11eb-906a-d153b0ff0d1b.jpeg)

Here is evidence

**Comment by danielkraak** [comment]
> ![CB8D2C82-9423-497F-8944-4065BBB25B57](https://user-images.githubusercontent.com/82219393/114189618-0194fd80-9910-11eb-8197-11eb262d7f8c.jpeg)
> ![389A1144-FBD1-49E8-A920-096053291BDC](https://user-images.githubusercontent.com/82219393/114189620-02c62a80-9910-11eb-906a-d153b0ff0d1b.jpeg)
> 
> Here is evidence

That is a clone device. We cannot guarantee that it will work properly with our software and apparently it does not.

**Comment by danielkraak** [comment]
> The disc could not be read error appears. The GC loader has two red lights on? I have a Sandisk Ultra Plus Micro SD card of 128GB. It is formatted to Fat32. I have a ntscUSA gamecube, so I used that iso. I renamed it boot. I don't know what's wrong

It is probably best to discuss these issues by contacting the place you bought it from. For example, if you got it from gc-loader.com or black-dog.tech, you can use their contact forms.

**Comment by tjanas** [comment]
@DefKonZer0 steer clear from buying fakes and especially AliExpress. Support the real developers. And typically you’ll get zero support from shady bootleggers in China.
