### ISSUE TITLE
GCLoader Force Resolution doesn't work for 240p

### ISSUE THREAD

**Issue by Foxe1559** [danielkraak/GC-Loader#18]
Forcing 240p doesn't work through swiss on items in the GCLoader but work perfectly fine when loaded through a memory card. For example, GBI loaded as 240p works great from the SD Card but loading Mario Kart DD as 240p from the GCLoader does not. 

My GCVideo still shows the resolution as something like 640x240 which is double the expected horizontal resolution. This seems to cause my CRTs to treat this as 480i instead of 240p like when loaded through other means.

**Comment by danielkraak** [comment]
I think 240p is typically sent as 640x240, but then horizontally each pixel is doubled making it 320 pixels effectively.

I am also missing some information here. Did you try to load Mario Kart DD also through your memory card/sd2ps2? How do you know your CRT treats it as 480i? A CRT typically doesn't do much processing to the image. If a progressive signal is sent to it (240p), I find it unlikely that it would convert it to 480i.

**Comment by Foxe1559** [comment]
Sorry, I was pretty tired when writing this. I must have been mistaken when I thought other forms of media worked. This might be an issue with either swiss or GCVideo actually and not the GC Loader. I had the same issue when loading Mario Kart DD from the SD2SP2 when trying to force 240p. Interestingly, GBI loads correctly onto my CRTs whereas regular games get the split screen treatment.

![image](https://user-images.githubusercontent.com/81350121/114372960-f8d24080-9b36-11eb-8493-05d2c94b87a3.png)


A bit of extra info though just so I have it written down somewhere. Forcing 240p results in 668x224p60 according to GCVideo's OSD. That seems "correct" given MK:DD runs at 448p.

Sorry for the false report. Again, tired. Thanks for making such a great product though. It was really easy to install and get running.
