### ISSUE TITLE
gcloader 2.0.0 firmware 

### ISSUE THREAD

**Issue by Sirethief2525** [danielkraak/GC-Loader#22]
I noticed in the change log for the new swiss version that gcloader 2.0.0 support is mentioned, I'm assuming that implies a new version of the firmware will drop at some point if not side by side? Not really an issue as much as it is a question about a possible release date or time frame as I love my gc loader and the possibility of new or upcoming features is exciting to me. Thank-you for all of your hard work and hope to hear from you soon.

**Comment by GabeShack** [comment]
I was interested in this little nugget of info as well.  Assuming the swiss team is most likely beta testing 2.0 was my guess.

**Comment by emukidid** [comment]
Yes, Extrems is beta testing it so support is effectively there already for it in Swiss.

**Comment by GabeShack** [comment]
Sweet! Thanks all for everything you do!

**Comment by Dodgyhodgy** [comment]
I’ve been using my GC Loader now for about 2 months and absolutely loving it. However booting it up this morning I was greeted with an error code “Exception (DSI) occurred!” and haven’t had any luck trying to resolve the situation. I’ve tried different firmware and formatting the SD card but run into the exact same error. At this point I’m thinking it must be some kind of hardware issue, any suggestions?

here’s an image of the full log displayed if it helps (apologies for the poor quality, I only have access to a CRT at the moment)
![5E1693F7-3908-4955-8895-73990EE4A1F5](https://user-images.githubusercontent.com/66674542/131432104-89ac9d77-ba54-4e34-a74e-b5bd2beb19fe.jpeg)

**Comment by GabeShack** [comment]
Would love to try version 2 beta and help knock out any issues.

**Comment by danielkraak** [comment]
Just uploaded the BETA.
