### ISSUE TITLE
Error code on boot

### ISSUE THREAD

**Issue by Dodgyhodgy** [danielkraak/GC-Loader#23]
I’ve been using my GC Loader now for about 2 months and absolutely loving it. However booting it up this morning I was greeted with an error code “Exception (DSI) occurred!” and haven’t had any luck trying to resolve the situation. I’ve tried different firmware and formatting the SD card but run into the exact same error. At this point I’m thinking it must be some kind of hardware issue, any suggestions?

here’s an image of the full log displayed if it helps (apologies for the poor quality, I only have access to a CRT at the moment)
![5B7175AB-3CF3-497F-A645-8F5F4A811071](https://user-images.githubusercontent.com/66674542/131432871-417fa732-ba69-4e46-8fbd-5468d9cb4888.jpeg)

**Comment by emukidid** [comment]
You're running into a bug that suggests the GameCube is being fed corrupt data from the SD card. Can you try another SD card?

**Comment by Dodgyhodgy** [comment]
Unfortunately I only have access to the one SD Card. Changing the boot iso just leads to a freeze during the first second of the GameCube intro. Guess my micro SD card is borked

**Comment by GabeShack** [comment]
Maybe try the new release of Swiss that just dropped?

**Comment by Extrems** [comment]
I hadn't added FST validation yet, but the underlying hardware issue would still exist anyway.

**Comment by GabeShack** [comment]
Any chance you are using an sd-extender? If so maybe try without it?

**Comment by Dodgyhodgy** [comment]
I feel like such an idiot, but it turns out that the culprit was a corrupted iso file all along. Strange considering every other file on the card gave me no issues, and the corrupted iso had been working fine up until recently. 

Thanks for all the suggestions.
