### ISSUE TITLE
Paper Mario 

### ISSUE THREAD

**Issue by Fredoias** [danielkraak/GC-Loader#27]
Audio de-syncs after 10 minutes or so. Up to 2 seconds behind on screen activity. Running 2.0 beta.

**Comment by Extrems** [comment]
I'm going to guess you're using GCVideo-DVI. In the GCVideo menu, go to Advanced Settings then turn on the Sample Rate Hack.

**Comment by Fredoias** [comment]
Thanks for the quick response, I'll check it out and ge you updated.

Thanks again.
Alfred

**Comment by Fredoias** [comment]
> I'm going to guess you're using GCVideo-DVI. In the GCVideo menu, go to Advanced Settings then turn on the Sample Rate Hack.

That was it, thank you!
