### ISSUE TITLE
GC Loader stopped working after FW update to 2.0 beta

### ISSUE THREAD

**Issue by serger94** [danielkraak/GC-Loader#28]
Hi, my GC Loader stopped working after I updated the fw to 2.0 (it was initially 1.12 when i got it from aliexpress). Now all I see is a red error message "the disc could not be read" as soon as I switch on the console. Before that, I was able to boot to Swiss and browse folders, however it wouldn't boot isos from the same sdhc card, saying this - "Disc does not contain valid word at 0x1C".
Now I have no clue how to fix this..

**Comment by tjanas** [comment]
Are you sure it’s a legitimate GCLoader? Genuine units are sold at https://www.black-dog.tech/gc-loader-pnp.html and I am not aware of any authorized dealers on aliexpress.

**Comment by serger94** [comment]
Well, I would buy it from black dog tech in a first place, but Out of Stock sign stopped me from doing it..
I was hoping to find some info on how to restore the device to its original firmware. Any tips on that?

**Comment by tjanas** [comment]
> I was hoping to find some info on how to restore the device to its original firmware. Any tips on that?

Contact the aliexpress seller.

**Comment by retrofank** [comment]
Your probably screwed.  Aliexpress sell clones, so it must have bricked on the 2.0 beta update.
