### ISSUE TITLE
Game seems to be incompatible 

### ISSUE THREAD

**Issue by Sirethief2525** [danielkraak/GC-Loader#4]
I have a copy of Midway Arcade Treasures 3 that loads fine and even works in the menu selection, but when I select a game it crashes and gives me the typical gamecube error message about powering it off. Any help you can give me would be much appreciated as this game has one of my favourite racing games on it. Thank-you in advance.

**Comment by Extrems** [comment]
I'm seeing the same on Rush 2049. DIP switch 4 isn't helping.

**Comment by Sirethief2525** [comment]
Okay, so I'm not the only one then. I've also got a copy of metroid prime 1.02 or something of that nature that stops loading after the retro studios screen and dip switch 4 doesn't help either.

**Comment by Sirethief2525** [comment]
What else do those dip switches do? I know on beta firmware if you flipped all 4 of them it would boot to the gc menu instead and you could load it just like a disc or hold a to auto boot the gc loader; so basically the reverse of what you did to get to them menu when they're all off.

**Comment by Extrems** [comment]
Sorry about that, it's a Swiss bug.

**Comment by Extrems** [comment]
Fixed in emukidid/swiss-gc@f5a42b2.

**Comment by danielkraak** [comment]
@Extrems To which post are you referring as being a Swiss bug? 

@Sirethief2525 Thanks for reporting the problem. I will start looking into compatibility issues very soon hopefully.

**Comment by Extrems** [comment]
They'd both be that bug.

**Comment by danielkraak** [comment]
Thanks. I will also test some other games, I noticed only had trouble when run through Swiss.

**Comment by Sirethief2525** [comment]
Thanks for responding so quick, I work over nights so when I get home in the morning I'll be sure to test it.

**Comment by Sirethief2525** [comment]
So I just realised that I'd have to compile that code into an dol file and then to an iso, I don't suppose that @Extrems you'd be able to do that for me eh?

**Comment by Extrems** [comment]
https://files.extremscorner.org/gamecube/apps/swiss/r788.7z

**Comment by Sirethief2525** [comment]
Thank-you @Extrems, everything seems to be working fine now except Metroid Prime, but it's a pretty old dump from a worn out disc that I've since replaced so I'll re-dump and let you know if that fixes it. @danielkraak the only other issue I've noticed is that the option for swiss's in-game-reset doesn't work right, it reboots the system but then throws an error message saying it can't read the disc and to look at the owners manual and all that jazz: so if you have a solution or an idea of what could potentially be causing that issue that'd be a big help. Thanks in advance.

**Comment by Sirethief2525** [comment]
Okay, so I've re-dumped and even downloaded another copy of Metroid Prime and none of them seem to work. I've tried various dip switch settings other than just the standard switch 4 and I guess I can confirm Metroid Prime as not working yet which is odd because Metroid Prime 2 works.. I even tried to use Metroid Prime as the boot file instead of Swiss and all that did was give me the " Cannot read this disc" error so I'm completely stumped as to why it isn't working. Sorry for all of the hassle with this because I know you all have other things and testing to do, thank-you in advance and for all of the help you've given thus far.

**Comment by danielkraak** [comment]
This is probably a timing issue in gc loader. Thanks for reporting it. I will look into it.

**Comment by Sirethief2525** [comment]
Not a problem, I don't know if you'd be interested or not but I can do beta testing for you with firmware updates and whatnot. I'd be pretty interested since I've never done anything like that before; but that's your call to make. Thanks again for your help and contributions to the scene.

**Comment by retrofank** [comment]
> Okay, so I've re-dumped and even downloaded another copy of Metroid Prime and none of them seem to work. I've tried various dip switch settings other than just the standard switch 4 and I guess I can confirm Metroid Prime as not working yet which is odd because Metroid Prime 2 works.. I even tried to use Metroid Prime as the boot file instead of Swiss and all that did was give me the " Cannot read this disc" error so I'm completely stumped as to why it isn't working. Sorry for all of the hassle with this because I know you all have other things and testing to do, thank-you in advance and for all of the help you've given thus far.

I'm still using swiss build r775 and NTSC/U Redump copies of MP 1 & 2 and they both load fine.  Only issue I had, was the audio on MP 1 was a bit distorted in places but there were no crashes.

**Comment by Sirethief2525** [comment]
I was going to get back on here the other day and let you know that it miraculously started working one day at random. The only thing I did different was use nkit to convert it from what it had been, and even the first time I tried it it didn't work, then the next day all of a sudden "boom" she worked as if nothing happened hahahaha. The version of swiss I'm using now is r788 where @Extrems fixed the Midway Arcade Treasures 3 issue, but couldn't seem to get it to work on r775. Oh and now the igr is also working where as it wasn't before with a similar "boom" moment of when that happened.

**Comment by Extrems** [comment]
Please don't ignore the "Disc shrunk using an unsupported tool." warning. It's there for a very good reason.

**Comment by Sirethief2525** [comment]
But the weird thing is that it never game me that error message on any of the dumps I tried, I did that as a last resort/ something has to work fix.

**Comment by Sirethief2525** [comment]
Most of the issue seems to have gone away except for the first need for speed underground but reconverting it might fix the issue. Thanks for all your help.
