### ISSUE TITLE
Gamecube boot sequence gets skipped

### ISSUE THREAD

**Issue by tedmahsun** [danielkraak/GC-Loader#6]
Just curious if this is normal behavior?
https://www.youtube.com/watch?v=cRNHyb3PexM

The Gamecube boot sequence immediately gets skipped before Swiss is loaded. It's so fast my OSSC barely has time to sync. I'm on firmware 1.0.1 and I'm wondering if the "decreased FPGA boot time" has anything to do with it?

**Comment by Extrems** [comment]
This is something Swiss is doing. It has nothing to do with the GC Loader.

**Comment by tedmahsun** [comment]
Ah I see. Ok, I'll go ask this on the Swiss github then. Thanks!
