### ISSUE TITLE
Distorted Audio in 1.0.1

### ISSUE THREAD

**Issue by etsuna2345** [danielkraak/GC-Loader#8]
Hi, sorry for my english. Thanks for the great product

In Ace Golf (Europe), sometimes when the ball is on the green, audio is distorted. Audio returns to normal when a new music started. There is random.

In Extrême G3 (US), there is the same bug in the race.

Perhaps, audio data is not loaded correctly randomly...

**Comment by FossilArcade** [comment]
Super Monkey Ball, occasional audio issues with music.

**Comment by tzakiel** [comment]
I’d love to see a response to this issue and a fix. It’s been a long time?

**Comment by danielkraak** [comment]
This has been fixed in 1.1.2.
